[template.environment]
  GQL_HOST = "WordPress URL http://example.com"
  NUXT_IMAGE_DOMAINS = "Comma separated list of domains. example.com,example2.com"

[build]
  command = "nuxt generate"

[images]
  # Repclace with your own domain to allow remote images to be optimized
  remote_images = ["https://secure.woonuxt.com/.*"]
