# [build]
  # functions = "functions"

[template.environment]
  WORDPRESS_URL = "Set this to your WordPress URL"
  
[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    # X-Frame-Options = "ALLOW-FROM https://testing.2cubedtest.com"
    # X-XSS-Protection = "1; mode=block"
    # Referrer-Policy = "no-referrer"
    # X-Content-Type-Options = "nosniff"
    # Strict-Transport-Security = "max-age=15780000; includeSubDomains; preload"
    # Feature-Policy = "geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'none'; payment 'none'"
    # Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline'"


[[redirects]]
  from = "/*"
  to = "https://testing.2cubedtest.com/:splat"
  status = 200